name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc5, gcc6, gcc7]
    runs-on: [self-hosted, docker]
    container:
      image: conanio/${{ matrix.compiler }}
      options: --user 1000:1000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install git
        run: apt install git
      - name: Configure
        run: python3 waf configure
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests
      - name: Status
        run: echo "Build ${{ job.status }}"
