name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc5, gcc6, gcc7, clang39, clang10]
        include:
          - compiler: gcc*
            gcc_problem_matcher: true
    runs-on: [self-hosted, docker]
    container:
      image: conanio/${{ matrix.compiler }}
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: python3 waf configure
      - uses: ammaraskar/gcc-problem-matcher@master
        if: matrix.gcc_problem_matcher
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests
      - name: Status
        run: echo "Build ${{ job.status }}"
