name: Build
on: [push, pull_request]
jobs:
  setup:
    runs-on: [self-hosted, docker]
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  gcc5:
    needs: setup
    runs-on: [self-hosted, docker]
    container:
      image: conanio/gcc5
      options: --user ${{ needs.setup.outputs.uid_gid }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install git
        run: apt install git
      - name: Install ssh
        run: apt-get -y update && apt-get -y upgrade && apt-get -y install ssh
      - name: Check version
        run: g++ --version
      - name: Configure
        run: python3 waf configure --git_protocol=git@
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests
      - name: Status
        run: echo "Build ${{ job.status }}"
