name: CMake
on: [push, pull_request]
jobs:
  # CMake build
  cmake_build:
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, macOS_X64, Linux]
    runs-on: [self-hosted, '${{ matrix.os }}', 'cmake']
    name: ${{ matrix.os }} CMake Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CMake Setup
        # Create a separate build directory
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: CMake Configure
        working-directory: ${{github.workspace}}/build
        run: cmake ${{github.workspace}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      - name: CMake Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
